### ISSUE TITLE
Compass Video Brainstorming

### ISSUE THREAD

**Issue by nicholasching** [sta-titansrobotics/Business-CENTERSTAGE#17]
The video must highlight how their mentor has helped them become an inspirational team. We want to hear what sets the mentor apart.

Criteria:

Video must follow FIRST branding and design standards.
Video cannot be longer than 60 seconds.
Video must be of a high quality, as submissions may be used later to promote FIRST.
Team must have rights to the music used in the video.
Music and permissions must be listed in video credits.
Video must have strong production value.
Video must be submitted by the deadline given by the tournament director.
Team must present a thoughtful and impactful video which appeals to the public.
Creativity in interpreting the yearly theme is required.

**Comment by nicholasching** [comment]
Brainstorming Ideas: 

First 10 Seconds - Montage Shots of Fabroa doing Stuff
10 - 20 Seconds - Compilation of words where Fabroa mentions
30 - 50 Seconds - Student catchphrase montage
50 - 60 Seconds - Catchphrase (FIRST inspires us to ... our mentor inspires us to ...)

**Comment by thatdudePranay** [comment]
Brainstorming Is Mostly Complete but open and ongoing for new ideas to be added, Shotclips to be started
