### ISSUE TITLE
Compass Video Shot List and Timeline Layout

### ISSUE THREAD

**Issue by thatdudePranay** [sta-titansrobotics/Business-CENTERSTAGE#29]

**Comment by nicholasching** [comment]
https://docs.google.com/document/d/1BNNWgscamSevtd9-UoGqvscjtIMrn7t5m6sGc3Zb4nw/edit?usp=sharing

**Comment by thatdudePranay** [comment]
[Recorded Shots](https://drive.google.com/drive/folders/1-Eskc1_Jw90E0ya8xlLaW_dAB1smXUt1?usp=sharing)
